//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /*! jQuery v1.12.5-pre | (c) jQuery Foundation | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m=&quot;1.12.5-pre e09907ce152fb6ef7537a3733b1d65ead8ee6303&quot;,n=function(a,b[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $(document).ready(function () {
        ///    $(document).on(&quot;click&quot;, &quot;th&quot;, function () {
        ///        location.href = &quot;event://th/click?columnIndex=&quot; + $(this).index() + &quot;&amp;rowIndex=&quot; + $(this).closest(&apos;tr&apos;).index() + &quot;&amp;data=&quot; + $(this).val();
        ///    });
        ///
        ///    $(document).on(&quot;click&quot;, &quot;td&quot;, function () {
        ///        location.href = &quot;event://td/click?columnIndex=&quot; + $(this).index() + &quot;&amp;rowIndex=&quot; + $(this).closest(&apos;tr&apos;).index() + &quot;&amp;data=&quot; + $(this).val();
        ///    });
        ///
        ///    $(document).on(&quot;change&quot;, &quot;th input:checkbox&quot;, function [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   html, body {
        ///    height: 100%;
        ///}
        ///
        ///body {
        ///    margin: 0;
        ///}
        ///
        ///table {
        ///    width: 100%;
        ///    height: 100%;
        ///    border-collapse: collapse;
        ///}
        ///
        ///table, th, td {
        ///    border: 1px solid #A9A9A9;
        ///}
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_full {
            get {
                return ResourceManager.GetString("style_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   html, body {
        ///    height: 100%;
        ///}
        ///
        ///body {
        ///    margin: 0;
        ///    display: flex;
        ///    flex-direction: column;
        ///}
        ///
        ///table {
        ///    width: 100%;
        ///    height: 100%;
        ///    border-collapse: collapse;
        ///}
        ///
        ///table, th, td {
        ///    border: 1px solid #A9A9A9;
        ///}
        ///
        ///table {
        ///    table-layout: fixed;
        ///    height: auto;
        ///}
        ///
        ///    table.head {
        ///        width: calc(100% - 17px);
        ///    }
        ///
        ///    table.body {
        ///        width: 100%;
        ///    }
        ///
        ///div.scroll-head {
        ///    /*background-color: #F0F0F0;*/
        ///}
        ///
        ///div.scroll-body table, div.sc[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string style_scroll {
            get {
                return ResourceManager.GetString("style_scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table&gt;
        ///        &lt;thead&gt;
        ///        &lt;/thead&gt;
        ///        &lt;tbody&gt;
        ///        &lt;/tbody&gt;
        ///    &lt;/table&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string table_full {
            get {
                return ResourceManager.GetString("table_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;scroll-head&quot;&gt;
        ///        &lt;table class=&quot;head&quot;&gt;
        ///            &lt;thead&gt;
        ///            &lt;/thead&gt;
        ///        &lt;/table&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;scroll-body&quot;&gt;
        ///        &lt;table class=&quot;body&quot;&gt;
        ///            &lt;thead&gt;
        ///            &lt;/thead&gt;
        ///            &lt;tbody&gt;
        ///            &lt;/tbody&gt;
        ///        &lt;/table&gt;
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string table_scroll {
            get {
                return ResourceManager.GetString("table_scroll", resourceCulture);
            }
        }
    }
}
